name: Lint

on:
  push:
    branches: [main, test_lint*]
    paths:
      - grammar.js
  pull_request:
    paths:
      - grammar.js

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:22-bookworm

    steps:
      - name: Print OS version
        run: |
          uname -a
          cat /etc/os-release

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
            ~/.cache/node-gyp
          key: ${{ runner.os }}-node22-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node22-

      - name: Install dependencies
        run: npm install --legacy-peer-deps --prefer-offline --no-audit --no-fund

      - name: Run ESLint
        run: npm run lint
