name: Publish package

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  crates:
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    with:
      package-name: tree-sitter-bpftrace
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_TOKEN}}
